### ISSUE TITLE
pie chart indicator

### ISSUE THREAD

**Issue by satviksun** [pyanfield/WSChart#7]
Hi,
Thank you so much for this code.
But I am unable to show indicator on slice of pie chart.
can u tell me how that works??

**Comment by pyanfield** [comment]
There are two pie classes WSPieChartView and WSPieChartWithMotionView.
But only WSPieChartView supports indicator.

https://github.com/pyanfield/WSChart/blob/master/WSCharts/Pie%20Chart/WSPieChartWithMotionView.h#L26-L30

**Comment by satviksun** [comment]
ok 
Thanks

**Comment by pyanfield** [comment]
I have added some sample codes and updated.
https://github.com/pyanfield/WSChart/blob/master/WSChartsDemo/WSChartsDemo/ViewController.m#L95-L100

**Comment by satviksun** [comment]
can we add both in a single pie chart?
Or can we detect and get information of opened slice of pie chart?
Mean when i click on slice 1 then it show all data of that slice which I wan to show user?

**Comment by satviksun** [comment]
can we add both in a single pie chart?
Or can we detect and get information of opened slice of pie chart?
Mean when i click on slice 1 then it show all data of that slice which I wan to show user?

**Comment by pyanfield** [comment]
sorry, I don't know what you mean.

**Comment by satviksun** [comment]
I want say that there is any way to join both filed means add indicator with motion.

**Comment by pyanfield** [comment]
yes , in the motion chart, the sections are in the different layers. You can draw the indicator in that layer.

**Comment by satviksun** [comment]
- (void)drawChart:(NSArray *)arr withColor:(NSDictionary *)dict;
  this function is not available in WSPieChartView so I am Unable to show indicator in pie chart. 
  Please give a solution for that.  So I can show indicator on pie chart with motion.

**Comment by pyanfield** [comment]
Did you pull the new code?
I have fixed this issue before.
